### ISSUE TITLE
Remove presence check from conformance statements

### ISSUE THREAD

**Issue by carolinerosin** [usnistgov/igamt#22]
The XML that is generated by IGAMT contains "Presence" checks that should not be there. For conformance statements, the Presence check should be removed.

Example : 
![image](https://user-images.githubusercontent.com/13591511/62544696-4957ad80-b82e-11e9-83fd-235a50434fb7.png)

Should be
![image](https://user-images.githubusercontent.com/13591511/62544743-62605e80-b82e-11e9-9826-ad05b427a8b8.png)

**Comment by carolinerosin** [comment]
Fixed

**Comment by carolinerosin** [comment]
We found an issue with Sandra that is probably related to that fix.
When the user adds a Presence check, it is not showing up in the Assertion and therefore creating invalid XML.
Only the Presence checks that were automatically added by IGAMT should have been removed - not the ones added by user

![image](https://user-images.githubusercontent.com/13591511/63867288-a30d4c80-c982-11e9-89d2-2a603c530ac8.png)

**Comment by Abdelghani90** [comment]
@carolinerosin do you still have this issue.

**Comment by carolinerosin** [comment]
I'll check - thanks !

**Comment by carolinerosin** [comment]
Nope, it's working !
