### ISSUE TITLE
"target" attribute is missing from conformance statements

### ISSUE THREAD

**Issue by carolinerosin** [usnistgov/igamt#24]
We we create conformance statements from the message level (either choosing the root message or a group as a context), the XML generated does not include the "Target" element in the Constraint element. Without that attribute (for message and group context), the profile viewer in GVT cannot display the conformance statement.
See screenshot. IZ-46 is correct (and was created in the past. IZ-205 and IZ-206 are missing "target". If we create new statements at that level (message), target is missing. If we delete existing statement and recreate them, "target" is missing.

![image](https://user-images.githubusercontent.com/13591511/62566468-05c56980-b857-11e9-8062-67872426df68.png)

**Comment by Jungyubw** [comment]
@carolinerosin 

I remeber that we cannot specify the targer location for some of conformance statement. So we discard targer attribute.

In the IGAMT, we are showing root for conformance statement. So I think GVT also need to show on the root, not any specific location.

We may need to discuss of this issue.

**Comment by carolinerosin** [comment]
The problem is that in GVT (and probably other tools ?) the profile viewer relies on the target attribute to display the conformance statement. So either we add target back in the XML generated by IGAMT (in that case we need to figure out what value to put in there) or the profile viewer needs to be updated in the  GVT/tool framework. We can discuss that next Monday with Rob and the rest of the team.

**Comment by carolinerosin** [comment]
After discussing with Nicolas - we probably need more info from Rob as we're not quite sure how to implement that in the profile viewer. For IGAMT, no action is needed
