### ISSUE TITLE
Conformance statement view at message level is sometimes messed up

### ISSUE THREAD

**Issue by carolinerosin** [usnistgov/igamt#25]
I see the same conformance statement in different groups, but it should only be in one group. I'm not sure how I got that and how to reproduce, it does not happen systematically. There is no OBX in PATIENT VISIT so that is not even possible to create

![image](https://user-images.githubusercontent.com/13591511/62566722-a61b8e00-b857-11e9-9182-b60186a1f06a.png)

**Comment by Jungyubw** [comment]
Maybe....did you modify message structure to remove OBX in PATIENT_VISIT?

I tried to make this situation, but I couldn't
