### ISSUE TITLE
Do not add additional Presence check in Predicate for a user Presence check

### ISSUE THREAD

**Issue by carolinerosin** [usnistgov/igamt#27]
When the user creates a condition predicate with a presence check, IGAMT automatically adds a second presence check. This is useless.
When I export the XML here is what I get:
![image](https://user-images.githubusercontent.com/13591511/62970251-1177d980-bddd-11e9-9b33-16bbf740bb4e.png)
 Here is what it should be
![image](https://user-images.githubusercontent.com/13591511/62970283-22c0e600-bddd-11e9-8f6b-a56b6315768d.png)

Solution is to remove the extra presence check in predicates when the user selects a presence check. Do not remove for other type of assertions (in predicates).

**Comment by carolinerosin** [comment]
It's not breaking anything - so no need to fix for the moment

**Comment by Jungyubw** [comment]
It is not breaking anything, but not good (it looks weird.).

I will fix it
