### ISSUE TITLE
XML Reserved Markup Characters are not escaped when creating a Plaintext Conformance statement

### ISSUE THREAD

**Issue by carolinerosin** [usnistgov/igamt#28]
I only tested the Plaintext assertion in Conformance statement. We need to check if this also applies to Predicate and if there are other assertion types that have the same issue.

Here's what I was able to generate
![image](https://user-images.githubusercontent.com/13591511/62971882-da0b2c00-bde0-11e9-9987-59f2f047c4e3.png)

This is not valid XML. The following characters should be escaped 
![image](https://user-images.githubusercontent.com/13591511/62971852-c233a800-bde0-11e9-89bf-2c50eaa4f610.png)

**Comment by Jungyubw** [comment]
fixed
