### ISSUE TITLE
Co-constraint OBX-2 dropdown menu out of sync 

### ISSUE THREAD

**Issue by carolinerosin** [usnistgov/igamt#32]
I created a flavor of 0125 to add the "CWE" code.
Then I created an OBX flavor and changed the OBX-2 value set to the one I created (to add CWE).
In co-constraints, I don't see "CWE" in the OBX-2 (value) dropdown.

To fix that, I need to go to my HL70125 flavor, change something, save and then go back to my OBX co-constraints. Afgter doing that, the dropdown menu is updated and I can see my CWE value

**Comment by Jungyubw** [comment]
I know this issue I will fix it..
