### ISSUE TITLE
Profile component/composite profile generates multiple flavors where one should be enough

### ISSUE THREAD

**Issue by carolinerosin** [usnistgov/igamt#34]
I'm not sure this is an issue or not, but it looks strange to me.
1. I create a OBX_ELR flavor
2. I change the flavor of OBX in my message structure at two different places
![image](https://user-images.githubusercontent.com/13591511/63710506-4cc7ce80-c807-11e9-8bdd-ac3f4453d129.png)
3. I create a profile component to change the usage of OBX_ELR-19 to R
![image](https://user-images.githubusercontent.com/13591511/63710541-6701ac80-c807-11e9-973b-495de4ff2ac3.png)
4. I export the XML profile, but there are two new flavors generated ?
![image](https://user-images.githubusercontent.com/13591511/63710637-a6c89400-c807-11e9-8dd3-c1c2489b5a5a.png)

**Comment by carolinerosin** [comment]
It seems to work correctly - but the two flavors look exactly the same

**Comment by Jungyubw** [comment]
In the current old IGAMT, profile component is applying one by one for each segment. Even there are no difference, we are making two different flavor.

I know it may not be efficient, but it is easier way to generate Composite profile.
