### ISSUE TITLE
Presence Check on CS

### ISSUE THREAD

**Issue by smartinez290** [usnistgov/igamt#35]
The following constraint failure is generated when there is no OBX segments in the message:

IZ-206 - If the value of OBX-3.1 (Identifier) is '30945-0' (Vaccination contraindication/precaution) then the value of RXA-20 (Completion Status) in the same Order Segment Group SHALL be 'NA'.
--

**Comment by smartinez290** [comment]
@Jungyubw I think @carolinerosin was working on this issue with @Abdelghani90. 
(one recommendation was to have the user mod the CS adding a presence check - if OBX-3.1 is value and … ) I recreated the CS adding  the presence check, but noticed that an assertion is not generated for it. Caroline indicated that it looks like the last fix for presence check created another issue. I am not able to push to GVT.

**Comment by smartinez290** [comment]
IG: HL7 Version 2.8.2 Implementation Guide: Immunization Messaging, Release 1.0 - US Realm - Published Dec 2018- Copy- Copy

under my account: sandra

**Comment by carolinerosin** [comment]
@smartinez290  think it was fixed - can you try to re-create the assertion (with the present check) ?

**Comment by smartinez290** [comment]
@carolinerosin I just did. It is working now.
