### ISSUE TITLE
Co-constraints validation 

### ISSUE THREAD

**Issue by smartinez290** [usnistgov/igamt#36]
Not sure why some co-constraints errors are not generated in the following scenarios (XML File already sent to Hossam for this issue) 
![image](https://user-images.githubusercontent.com/14842422/63871834-a0165a00-c98a-11e9-811e-c6f513d42b98.png)

![image](https://user-images.githubusercontent.com/14842422/63871850-a6a4d180-c98a-11e9-8bc3-d82bb5c6b5e4.png)

**Comment by smartinez290** [comment]
@Jungyubw I am not sure if this issue is for you. I gave the info to Hossam in an email. It look like I can assigned it Hossam under this github account.

**Comment by Jungyubw** [comment]
@smartinez290  
If it is old IGAMT issue, I will look at it. If I need Hossam's help, I will do that.
Thanks.

**Comment by smartinez290** [comment]
IG: NIST HL7 Tooling QA 
Profile: Z22_QA_Profile_3
