### ISSUE TITLE
Constrain Pattern: "Shall be greater than the value of another node" 

### ISSUE THREAD

**Issue by smartinez290** [usnistgov/igamt#37]
Validator is triggering an error when the node is an empty value -- treating as 0. Should this be an error?

PID|1||D26376273^^^NIST MPI^MR||Snow^Madelynn^Ainsley^^^^L|Lam^Morgan^^^^^M|20070706|F||2076-8^Native Hawaiian or Other Pacific Islander^CDCREC|32 Prescott Street Ave^^Warwick^MA^02452^USA^L||^PRN^PH^^^657^5558563|||||||||2186-5^non Hispanic or Latino^CDCREC

Error: The value of PID-10[*].1 SHALL be greater than the value of PID-10[*].4.

**Comment by Jungyubw** [comment]
@smartinez290 

I think PID-10.1 is not number : 2076-8 and PID-10.4 is missing.
What do you want to compare these two value?

Also, if you want to treat as 0 for missing value, that should be interpreted by Hossam's validation tool.

**Comment by smartinez290** [comment]
@Jungyubw I just wanted to test the CS pattern. 
I am not sure if a missing value should be treated as 0. But, I just placed a number in PID-10.1 that is smaller than the one in PID-10.4 and I am still getting an error.

**Comment by Jungyubw** [comment]
@smartinez290  
Okay I will check with Hossam. I think validation tool does not consider empty value for comparison.
