### ISSUE TITLE
Assertion tag missing from XML for Plugin constraint (profile component)

### ISSUE THREAD

**Issue by carolinerosin** [usnistgov/igamt#38]
The XML generated by IGAMT is invalid and cannot be exported to GVT. This is an urgent one !
Here is what I have
![image](https://user-images.githubusercontent.com/13591511/64190795-21fffa80-ce45-11e9-88bf-d1fadcf7c5e6.png)

Here is what it should be
![image](https://user-images.githubusercontent.com/13591511/64190849-42c85000-ce45-11e9-9805-b2710f6b049b.png)

This is a conformance statement that was added in a profile component (if that helps)

**Comment by carolinerosin** [comment]
Note that this was working a few days ago - so it's probably a "fix" that broke it

**Comment by Jungyubw** [comment]
fixed
