### ISSUE TITLE
Removing a value set from a profile component item is not possible

### ISSUE THREAD

**Issue by carolinerosin** [usnistgov/igamt#46]
A user can only replace a value set on a profile component item. Removing (and not assigning another value set should be possible).

![image](https://user-images.githubusercontent.com/13591511/64377746-15bc9e80-cff9-11e9-8ea4-4bc0712dfc0e.png)

Side note: removing a value set binding that is Suggested (binding strength = S) is OK. If Binding Strength is Required, this is a compliance issue and should be reported in profile verification. I don't think it is going to be implemented in old IGAMT though.

**Comment by Jungyubw** [comment]
@carolinerosin If I understand correctly, this profile component is message level for OBX_ELR.
In this case OBX_ELR.17 has value set by segment level. You can replace new Valueset by message level. you cannot remove the value set, becasue it is semgent level. If you want to remove value set, you should create another profile component by Segment level.

Actually we have same issue on general message. We didn't consider to remove value set from the higher level. We may need to dicuss more...

**Comment by Jungyubw** [comment]
We will add null-valueset binding  for any level.

**Comment by carolinerosin** [comment]
@Jungyubw just checking if you are working on that one, I got another request today to be able to remove some value sets in the profile component (not just replace unfortunately). Let me know when this one is fixed.

**Comment by Jungyubw** [comment]
@carolinerosin I am woring on. New fix will be depoyed on Monday. Thanks.

**Comment by carolinerosin** [comment]
Perfect, thank you !

**Comment by Jungyubw** [comment]
Fixed and @Abdelghani90 Please deploy the tool. Thanks.

**Comment by Jungyubw** [comment]
@carolinerosin I have changed some of logic for valueset binding for PC.
If you click X icon then, you can see the NULL valueset binding. If you click X icon again, you can see the original value set from Conformance Profile.

Please test it after deployment.

Thanks.

**Comment by carolinerosin** [comment]
Has this one been deployed yet ?

**Comment by Abdelghani90** [comment]
not yet I will do it ASAP
