### ISSUE TITLE
Can't save updates to OBX flavor

### ISSUE THREAD

**Issue by smartinez290** [usnistgov/igamt#47]
Can't save updates to OBX 

User tried to delete the user Dynamic table.  Igamt frozed after clicking the save button. 

This is Mead's IG: HL7 Version 2.6 Implementation Guide-Vital Records Death Reporting, Release 1 STU 2- Updated

**Comment by Abdelghani90** [comment]
please share with me

**Comment by Jungyubw** [comment]
@smartinez290 I have fixed it. Please try again after deployment. I will ask to @Abdelghani90 to deploy it.

Thanks.

**Comment by smartinez290** [comment]
@Jungyubw Ok! Let me know when IGAMT is deployed please.
