### ISSUE TITLE
Adding a plugin conformance statement for a datatype is not possible

### ISSUE THREAD

**Issue by carolinerosin** [usnistgov/igamt#48]
I don't get the text boxes to enter the description and the plugin class name when I try to add a conformance statement on a datatype
![image](https://user-images.githubusercontent.com/13591511/64884010-a402d700-d62e-11e9-81c1-56544db6dad7.png)

This is what it looks like for segments
![image](https://user-images.githubusercontent.com/13591511/64884073-ceed2b00-d62e-11e9-91db-9ba51881fbc3.png)

**Comment by Jungyubw** [comment]
fixed
